Feat/list view and grid view
ZupIT/beagle-flutter pull request #21
Opened 2021-09-17 00:09 UTC by uziasferreirazup

### Related Issues

### Description and Example

### Checklist

Please, check if these important points are met using `[x]`:

- [ ] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [ ] I am willing to follow-up on review comments in a timely manner.
- [ ] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/main/doc/contributing/pull_requests.md

2021-09-17 00:10 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-09-17 00:15 UTC, botbeaglezup commented
<!--
  0 Errors
  3 Warnings: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-flutter/blob/ff7f81c6d41cf4ae8b2882ddfd2bc0a159d802ed/beagle/test/bridge_impl/global_context_js_test.dart#L97">beagle/test/bridge_impl/global_context_js_test.dart#L97</a> - The type argument(s) of the function 'get' can't be inferred</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-flutter/blob/ff7f81c6d41cf4ae8b2882ddfd2bc0a159d802ed/beagle/test/bridge_impl/global_context_js_test.dart#L109">beagle/test/bridge_impl/global_context_js_test.dart#L109</a> - The type argument(s) of the function 'get' can't be inferred</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle-flutter/blob/ff7f81c6d41cf4ae8b2882ddfd2bc0a159d802ed/beagle_components/lib/src/beagle_screen.dart#L55">beagle_components/lib/src/beagle_screen.dart#L55</a> - 'textTheme' is deprecated and shouldn't be used. This property is no longer used, please use toolbarTextStyle and titleTextStyle instead. This feature was deprecated after v2.4.0-0.0.pre.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-09-29 13:36 UTC, hernandazevedozup commented on beagle_components/lib/src/default_components.dart
> +        beagleWidgetStateProvider: BeagleWidgetStateProvider(),
Nice !

2021-09-29 13:37 UTC, hernandazevedozup commented on beagle_components/lib/src/utils/beagle_widget_state_provider.dart
> +class BeagleWidgetStateProvider {
Nice implementation, we can now refactor where we need this implementation to use this class. I think we use this also on SimpleForm.

2021-09-29 13:38 UTC, hernandazevedozup submitted a review, later dismissed

2021-09-29 13:53 UTC, arthurbleilzup requested changes

2021-09-29 13:53 UTC, arthurbleilzup commented on beagle_components/lib/src/dynamic_list/beagle_dynamic_list.dart
> +          mode: null,
you do not need to set the `mode`, if you want to set, please use `TreeUpdateMode.replace`

2021-09-29 14:09 UTC, arthurbleilzup approved these changes

2021-09-29 14:19 UTC, merged