:sparkles: Separate yoga from Widgets.
ZupIT/beagle-flutter pull request #22
Opened 2021-09-21 18:09 UTC by hernandazevedozup

2021-09-21 18:10 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  1 Warning: Please provide a summary in th...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-09-21 18:15 UTC, botbeaglezup commented
<!--
  1 Error: Could not run lint without set...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Could not run lint without setting report path or report file doesn't exists</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-09-23 19:32 UTC, botbeaglezup commented on beagle/lib/src/beagle_flex_widget.dart
> +Widget BeagleFlexWidget({BeagleStyle style, List<Widget> children}) {
<table data-meta="generated_by_flutter">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle-flutter/blob/baa4565ad5f712fe2c0275093cbfebd7e6b6cdef/beagle/lib/src/beagle_flex_widget.dart#L22"></span>Name non-constant identifiers using lowerCamelCase</td>
    </tr>
  </tbody>
</table>

2021-09-23 20:25 UTC, botbeaglezup commented on beagle/lib/src/beagle_yoga_layout.dart
> +import 'package:beagle/src/model/beagle_metadata.dart';
<table data-meta="generated_by_flutter">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle-flutter/blob/7f3740a7e26ca97995d3981015a9116723abcad4/beagle/lib/src/beagle_yoga_layout.dart#L20"></span>Unused import: 'package:beagle/src/model/beagle_metadata.dart'</td>
    </tr>
  </tbody>
</table>

2021-09-24 12:59 UTC, Tiagoperes commented on sample/lib/app_design_system.dart
> +    switch (id) {
Why did you a switch-case for a single condition?

2021-09-24 13:24 UTC, Tiagoperes commented on sample/lib/app_design_system.dart
> +    switch (id) {
Suggestion: If you need different button styles for different ids, prefer maps over switch-case, it's easier to read. Example:

```dart
final Map<String, BeagleButtonStyle> buttonStyles = {
  "DesignSystem.Stylish.MyFirstStyle": BeagleButtonStyle(...),
  "DesignSystem.Stylish.MySecondStyle": BeagleButtonStyle(...),
  "DesignSystem.Stylish.MyThirdStyle": BeagleButtonStyle(...),
}

@override
BeagleButtonStyle buttonStyle(String id) {
 return buttonStyles[id];
}
```

2021-09-24 13:35 UTC, Tiagoperes submitted a review, later dismissed

2021-09-24 17:15 UTC, uziasferreirazup requested changes

2021-09-24 17:15 UTC, uziasferreirazup commented on beagle/lib/src/beagle_flex_widget.dart
> +Widget BeagleFlexWidget({BeagleStyle style, List<Widget> children}) {
It doesn't convert the yoga layout widget to a real widget of ours if you look at the hierarchy, you can see that the user is seeing yogalayout and that can't happen.
![Screen Shot 2021-09-24 at 14 04 37](https://user-images.githubusercontent.com/63263091/134713936-137e8429-dc74-49b9-97a9-43c2dafc1097.png)

I recommend creating a real widget:

```
class BeagleFlexWidget extends StatelessWidget {
  const BeagleFlexWidget({
    Key key,
    this.style,
    this.children,
  }) : super(key: key);

  final BeagleStyle style;
  final List<Widget> children;

  @override
  Widget build(BuildContext context) {
    return beagleServiceLocator<BeagleYogaFactory>().createYogaLayout(
      style: style,
      children: children,
    );
  }
}

```
the result:


![Screen Shot 2021-09-24 at 14 14 02](https://user-images.githubusercontent.com/63263091/134714997-4deb315d-fc60-4a81-9c97-a7a370c4aec3.png)

2021-09-24 17:15 UTC, uziasferreirazup requested changes

2021-09-24 17:15 UTC, uziasferreirazup commented on beagle/lib/src/beagle_flex_widget.dart
> +Widget BeagleFlexWidget({BeagleStyle style, List<Widget> children}) {
You can add a unit tests to this class too.

2021-09-24 17:16 UTC, uziasferreirazup requested changes

2021-09-24 17:16 UTC, uziasferreirazup commented on beagle/lib/src/beagle_yoga_layout.dart
> +class BeagleYogaLayout extends YogaLayout {
What do you think about add a unit tests to this class?

2021-09-24 17:19 UTC, uziasferreirazup requested changes

2021-09-24 17:19 UTC, uziasferreirazup commented on beagle/lib/src/style/style_builder.dart
>  class BeagleYogaFactory {
this got kind of weird, because now you're returning a `BeagleYogaLayout ` in a method called `createYogaNode `

if you are going to follow the above suggestion of creating a widget, this factory makes no more sense to exist and can be deleted.

2021-09-24 17:22 UTC, uziasferreirazup requested changes

2021-09-24 17:22 UTC, uziasferreirazup commented on beagle/lib/src/beagle_flex_widget.dart
> +mixin RootAsFlexWidget {}
I understand you created the mix to know if it's beagle view or not, but isn't there any way to try to get it by widget type? or your first child? with that, it would be more automatic without the user needing to add this tag

2021-09-24 17:22 UTC, uziasferreirazup commented on beagle/lib/src/beagle_flex_widget.dart
> +mixin RootAsFlexWidget {}
```suggestion
mixin BeagleRootFlexLayoutWidget {}
```

or

```suggestion
mixin BeagleRootFlexViewWidget {}
```

2021-09-24 17:30 UTC, uziasferreirazup requested changes

2021-09-24 17:30 UTC, uziasferreirazup commented on beagle/lib/src/beagle_widget.dart
> +  BeagleYogaFactory beagleYogaFactory = beagleServiceLocator();
```suggestion
```
is this variable being used?

2021-09-24 17:34 UTC, uziasferreirazup requested changes

2021-09-24 17:34 UTC, uziasferreirazup commented on beagle_components/lib/src/beagle_simple_form.dart
> +    return BeagleFlexWidget(
you now need to get the style to work the positioning, the same code has in the beaglecontainer

2021-09-24 17:36 UTC, uziasferreirazup requested changes

2021-09-24 17:36 UTC, uziasferreirazup commented on beagle_components/lib/src/default_components.dart
> +    key: element.getKey(),
is this indentation correct? I entered the same code and sent it indented and it returned to the way it was.

2021-09-24 18:13 UTC, hernandazevedozup commented on beagle/lib/src/style/style_builder.dart
>  class BeagleYogaFactory {
I need the factory to be responsible of instantiation for the yoga infrastructure, because its the way we are mocking this layer for unit tests

2021-09-24 18:16 UTC, hernandazevedozup commented on beagle_components/lib/src/beagle_simple_form.dart
> +    return BeagleFlexWidget(
indeed

2021-09-24 18:41 UTC, hernandazevedozup commented on beagle/lib/src/beagle_flex_widget.dart
> +mixin RootAsFlexWidget {}
This is something we dont know how to do yet. Maybe we can create an issue to solve this later.

2021-09-24 19:27 UTC, hernandazevedozup commented on beagle/lib/src/beagle_yoga_layout.dart
> +class BeagleYogaLayout extends YogaLayout {
Currently we cannot mock this class dependencies as the yoga_engine does not make this easy for us. for now this class cannot have tests

2021-09-25 23:04 UTC, uziasferreirazup approved these changes

2021-09-25 23:04 UTC, merged