Feat/complex navigation: Part 1
ZupIT/beagle-flutter pull request #26
Opened 2021-09-27 17:51 UTC by Tiagoperes

2021-09-27 17:58 UTC, botbeaglezup commented
<!--
  0 Errors
  2 Warnings: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-09-27 18:02 UTC, botbeaglezup commented
<!--
  1 Error: Could not run lint without set...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Could not run lint without setting report path or report file doesn't exists</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-09-28 13:07 UTC, botbeaglezup commented on beagle/lib/src/bridge_impl/beagle_view_js.dart
> +import 'dart:developer';
<table data-meta="generated_by_flutter">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle-flutter/blob/12585591fa2e464c8881ea7ff19a1b514a85c8eb/beagle/lib/src/bridge_impl/beagle_view_js.dart#L18"></span>Unused import: 'dart:developer'</td>
    </tr>
  </tbody>
</table>

2021-09-28 13:07 UTC, botbeaglezup commented on beagle/lib/src/bridge_impl/beagle_view_js.dart
> +import 'dart:ffi';
<table data-meta="generated_by_flutter">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle-flutter/blob/12585591fa2e464c8881ea7ff19a1b514a85c8eb/beagle/lib/src/bridge_impl/beagle_view_js.dart#L19"></span>Unused import: 'dart:ffi'</td>
    </tr>
  </tbody>
</table>

2021-09-28 13:07 UTC, botbeaglezup commented on beagle/lib/src/default/default_actions.dart
> +import 'dart:developer';
<table data-meta="generated_by_flutter">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle-flutter/blob/12585591fa2e464c8881ea7ff19a1b514a85c8eb/beagle/lib/src/default/default_actions.dart#L17"></span>Unused import: 'dart:developer'</td>
    </tr>
  </tbody>
</table>

2021-09-28 13:07 UTC, botbeaglezup commented on beagle_components/lib/src/beagle_screen.dart
> +import 'dart:developer';
<table data-meta="generated_by_flutter">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle-flutter/blob/12585591fa2e464c8881ea7ff19a1b514a85c8eb/beagle_components/lib/src/beagle_screen.dart#L17"></span>Unused import: 'dart:developer'</td>
    </tr>
  </tbody>
</table>

2021-09-28 19:19 UTC, uziasferreirazup submitted a review, later dismissed

2021-09-28 20:12 UTC, hernandazevedozup commented on beagle/lib/src/beagle_widget.dart
> +/// use. To make sure it's ready, call `await beagleServiceLocator.allReady()`.
Can we not ask the user to call this await for now. I think that if in the future we remove the getit dependency from the project, the user will also have to remove the beagleServiceLocator.allReady() call.

2021-09-28 20:16 UTC, hernandazevedozup approved these changes

2021-09-28 20:19 UTC, hernandazevedozup requested changes
Please see the comments

2021-09-29 14:28 UTC, arthurbleilzup submitted a review, later dismissed

2021-09-29 19:38 UTC, Tiagoperes commented on beagle/lib/src/beagle_widget.dart
> +/// use. To make sure it's ready, call `await beagleServiceLocator.allReady()`.
My last commit solves this problem.

RootNavigator, StackNavigator and BeagleWidget all needed the BeagleService to be ready before being created.

Now, only the StackNavigator does. Since the StackNavigator is always created to be a child of the RootNavigator, it makes no sense for it to also wait the BeagleService to be ready. I added some documentation to reflect this.

The BeagleWidget now waits the BeagleService to be ready. But, to not make everything too complex, I created an UnsafeBeagleWidget. The UnsafeBeagleWidget assumes the BeagleService exists already, so I can keep using it inside the StackNavigator, where I'm sure the BeagleService is ready.

I could refactor everything to have a single safe BeagleWidget, but I tried this once, it's far too complicated, the BeagleView is never ready when I need to use it. Doing this would just make everything unnecessarily complex, just to probably remove it some sprints later, when the GetIt dependency is removed.

2021-09-29 19:40 UTC, hernandazevedozup submitted a review, later dismissed

2021-09-29 20:18 UTC, uziasferreirazup approved these changes

2021-09-29 20:25 UTC, Tiagoperes commented
Closing due to DCO restrictions.

2021-09-29 20:25 UTC, closed without merging